### ISSUE TITLE
HUD Reject switch binding

### ISSUE THREAD

**Issue by MadKreator37** [HeliosProfiles/DCS-F-15E-Profile-by-MadKreator37#4] opened 2023-08-27 03:25 UTC
HUD symbology reject switch on Pilot UFC reversed. Opposite movement between Helios switch and in-game switch. Switch does not seem to be implemented at this time, though.

**Comment by BlueFinBima** [comment] 2023-08-27 11:24
@MadKreator37 Typically the issue is raised against the repo with the error.  I suggest you close this as a duplicate of https://github.com/HeliosVirtualCockpit/Helios/issues/753

**Closed** 2023-08-27 15:32 UTC
